### ISSUE TITLE
Implement `before_all` and `after_all`

### ISSUE THREAD

**Issue by mackwic** [rust-rspec/rspec#20]
As of today, we only have `before_each` and `after_each`. Implementing the `after_all` and `before_all` should be a piece of cake.

**Comment by JustinRyanH** [comment]
How up to date is this Issue? I'm interested in contributing

**Comment by regexident** [comment]
Implemented in https://github.com/rust-rspec/rspec/pull/30

**Comment by mackwic** [comment]
@JustinRyanH there is work to do on the formatters if you want to start with something no too hard but very useful. ;)

**Comment by regexident** [comment]
@JustinRyanH Also don't hesitate to ask questions. You will probably have a bunch.

This being said I think I should write a documentation on the internal structure once I find the time.
As in "what is happening when and how/why during a test suite execution?".
