### ISSUE TITLE
Documentation link is dead

### ISSUE THREAD

**Issue by Horgix** [rust-rspec/rspec#34]
The Readme mention https://mackwic.github.io/rspec as the source for documentation but can be found there except "Sorry this page does not exist =( " 🙁 

This link is also the one associated to the Github repo, along the description.

**Comment by mackwic** [comment]
Yes, I moved this repository to an organization last week.

The link should be https://docs.rs/rspec anyway

**Comment by Horgix** [comment]
Submitted #35 to solve this. No idea why Github doesn't  track it here.

@mackwic : make sure to change the link in the Github repo "metadata" too if you were to merge #35 🙂
