### ISSUE TITLE
It isn't clear how to make use of this library

### ISSUE THREAD

**Issue by LaylConway** [rust-rspec/rspec#46]
Both the readme and the examples put the test code in main, but an average library isn't going to have a main, and an average binary is going to want to use that main for its own code. Is it supposed to be in an added binary? It's not entirely clear how this is supposed to be used.

**Comment by mackwic** [comment]
Thanks for you feedback ! Do you have a specific library in mind ? I can make you a PR with an example which use RSpec. In fact, we desperately need real world example, as your issue outline it.

You can use `#[test]` functions to put the Rspec suites, would them be embedded in your files or in integration tests (the `test/` directory). With a real file it would be easier, is your code open source ?

**Comment by LaylConway** [comment]
I don't currently have the project I want to use rspec for open source. I do however have a file from another project that may be a good real-world-ish example, with how I wrote its tests using the normal rust tests.

```rust
use nalgebra::{Vector2, Point2};

pub struct Map {
    tiles: Vec<Option<()>>,
    size: Vector2<i32>,
    player_spawn: Point2<f32>,
}

impl Map {
    pub fn new(size: Vector2<i32>) -> Self {
        Map {
            tiles: vec![None; (size.x * size.y) as usize],
            size,
            player_spawn: Point2::new(0.0, 0.0),
        }
    }

    pub fn size(&self) -> Vector2<i32> {
        self.size
    }

    pub fn player_spawn(&self) -> Point2<f32> {
        self.player_spawn
    }

    pub fn set_player_spawn(&mut self, position: Point2<f32>) {
        self.player_spawn = position
    }

    pub fn add_enemy_spawn(&mut self, _position: Point2<f32>) {
    }

    pub fn get_at(&self, position: Point2<i32>) -> Result<Option<()>, MapError> {
        if self.in_bounds(position) {
            Ok(self.tiles[self.index_at(position)])
        } else {
            Err(MapError::OutOfBounds { position })
        }
    }

    pub fn set_at(&mut self, position: Point2<i32>, value: Option<()>) -> Result<(), MapError> {
        if self.in_bounds(position) {
            let index = self.index_at(position);
            self.tiles[index] = value;
            Ok(())
        } else {
            Err(MapError::OutOfBounds { position })
        }
    }

    fn in_bounds(&self, position: Point2<i32>) -> bool {
        if position.x >= 0 && position.y >= 0 &&
           position.x < self.size.x && position.y < self.size.y {
            true
        } else {
            false
        }
    }

    fn index_at(&self, position: Point2<i32>) -> usize {
        (position.x + position.y * self.size.x) as usize
    }
}

#[derive(Debug, PartialEq)]
pub enum MapError {
    OutOfBounds { position: Point2<i32> },
}

#[cfg(test)]
mod tests {
    use nalgebra::{Vector2, Point2};
    use model::{Map, MapError};

    #[test]
    fn it_gets_error_for_out_of_bounds() {
        let map = Map::new(Vector2::new(1, 1));
        let position1 = Point2::new(3, 3);
        let position2 = Point2::new(-3, -3);

        assert_eq!(map.get_at(position1), Err(MapError::OutOfBounds { position: position1 }));
        assert_eq!(map.get_at(position2), Err(MapError::OutOfBounds { position: position2 }));
    }

    #[test]
    fn it_gets_value_after_set() {
        let mut map = Map::new(Vector2::new(5, 5));
        let position1 = Point2::new(3, 3);
        let position2 = Point2::new(1, 3);

        map.set_at(position1, Some(())).unwrap();
        map.set_at(position2, None).unwrap();

        assert_eq!(map.get_at(position1), Ok(Some(())));
        assert_eq!(map.get_at(position2), Ok(None));
    }

    #[test]
    fn it_returns_error_for_out_of_bounds_set() {
        let mut map = Map::new(Vector2::new(5, 5));

        let result = map.set_at(Point2::new(10, 10), Some(()));

        assert!(result.is_err());
    }
}
```

**Comment by mackwic** [comment]
Hi @LaylConway , here is my take on your file: https://gist.github.com/mackwic/08b7b8bb1b88058401f4b1bb0cc69f14 

Some remarks:
- there is commented test because of a weird bug in the Rspec runner (bug that I am not interested in fixing right now)
- while the environment works well for non-mutable data, it doesn't work at all with mutable data (ie, when testing `Map::set_at`)

So, I wouldn't recommend you to use Rspec outside of pedagogical purposes. This lib is not done yet. I hope you will still learn something from this snippet. I am always happy to help.

**Comment by mackwic** [comment]
closing because I gave you an example, even if not perfect. Feel free to re-open if you need anything else ❤️

**Comment by regexident** [comment]
> - there is commented test because of a weird bug in the Rspec runner (bug that I am not interested in fixing right now)

Is there an issue for this bug you're talking about, or could you briefly elaborate?

> - while the environment works well for non-mutable data, it doesn't work at all with mutable data (ie, when testing Map::set_at)

It does work with mutable data (via `ctx.before(…)`, in which one has mutable access to `map`). What does not work is testing mutating instance functions that return anything but `()`.
Unfortunately I don't see an easy fix for this right now. ☹️
