### ISSUE TITLE
Canary: Is this project alive or dead?

### ISSUE THREAD

**Issue by ms-ati** [rust-rspec/rspec#47]
This is a canary question -- is this project alive or dead?

If this just sits here, then future visitors on github can have an easier time discovering that's dead. If the issue is answered and discussion ensues, it's alive.

**Comment by mackwic** [comment]
It's neither. We (me and @regexident) are here, but maintaining this project is not our full time job. We do as much as we can and keeping our life.

Contributions are welcome, but given the current state of the project, I expect some kind of commitment from the contributors and stay a little, not a PR hit&run.

I hope that answer your question. I am closing this now. Feel free to ask any precision or help in any way. It's always welcome. :)

**Comment by ms-ati** [comment]
Thanks for your prompt response @mackwic. If you are responding then it's mostly alive. Is there any interest in joining a greater community of **BDD in Rust**?

I ask because one of the most popular rspec-like projects, https://github.com/reem/stainless, appears to be dead now. As a true newcomer, I thought it would be a great time to test the waters to see if the remaining projects such as https://github.com/utkarshkukreti/speculate.rs and this rust-rspec project might be interested in forming a merged community, to maximize the flow of newcomers, users, ideas, and PRs?

Note that I'm not implying combining the codebases -- just asking about the communities. A shared gitter room for example, and cross-links from each project explaining the differences?

**Comment by mackwic** [comment]
The main difference is the commitment of rspec to work with stable rust, which implies to not use macros, FnBox, and the like.

About the communities, do you think of something in particular ? I don't think there is real communities around these projects. Reem is doing many things which drive a lot of people around its work, but it's not really stainless related.

**Comment by regexident** [comment]
@ms-ati I've unfortunately been rather busy recently, so couldn't dedicate any time to rspec.

While the main project has indeed been somewhat stale I have been doing some experimentation in [rust-rspec/experiments](https://github.com/rust-rspec/experiments) for a while now, including multiple takes on improvements to rspec's syntax, as well as tagging.

I just pushed a new and promising experiment which I had laying on my computer for months, but forgot to push to Github: [macro](https://github.com/rust-rspec/experiments/blob/master/macro/). It [drastically simplifies the syntax](https://github.com/rust-rspec/experiments/blob/master/macro/src/main.rs#L390-L416) by implementing a macro-based DSL, inspired by @DenisKolodin's [yew](https://github.com/DenisKolodin/yew) project.

I cannot find the Github issue right now, but @mackwic mentioned an architectural flaw in the current implementation in a comment, that basically prevents (or at least makes it really difficult?) use of rspec for certain APIs. Something related to `fn foo(&mut self, …)`, iirc. Do you remember, @mackwic and if you do, could you create a dedicated issue for it?

**Comment by regexident** [comment]
> I cannot find the Github issue right now, but @mackwic mentioned an architectural flaw in the current implementation in a comment, that basically prevents (or at least makes it really difficult?) use of rspec for certain APIs. Something related to fn foo(&mut self, …), iirc. Do you remember, @mackwic and if you do, could you create a dedicated issue for it?

Found the comment: https://github.com/rust-rspec/rspec/issues/46#issuecomment-355834218
